(set-logic HORN)
(set-option :fp.xform.inline_linear false)
(set-option :fp.xform.inline_eager false)
(declare-fun P0 (Int) Bool)
(declare-fun P1 (Bool) Bool)
(assert (P1 false))
(assert (=> (exists ((r0 Bool)) (= (P1 r0) true)) (P0 0)))
(check-sat)
(get-model)