(set-logic HORN)
(set-option :fp.xform.inline_linear false)
(set-option :fp.xform.inline_eager false)
(declare-fun P2 (Int) Bool)
(declare-fun P1 (Bool) Bool)
(declare-fun P0 (Bool) Bool)
(assert (P0 true))
(assert (forall ((c0 Bool)) (=> (P0 c0) (P1 c0))))
(assert (forall ((c0 Bool)) (=> (and (P1 c0) (= c0 true) true) (P2 1))))
;(assert (forall ((x Int) (y Bool)) (=> (P1 y) (P1 false))))
(check-sat)
(get-model)
