(set-logic HORN)
(set-option :fp.xform.inline_linear false)
(set-option :fp.xform.inline_eager false)
(declare-fun P0 (Int) Bool)
(declare-fun P20 (Int) Bool)
(declare-fun P28 (Bool) Bool)
(declare-fun P16 (Bool) Bool)
(declare-fun P2 (Bool) Bool)
(declare-fun P22 (Int) Bool)
(declare-fun P54 (Int) Bool)
(declare-fun P27 (Int) Bool)
(declare-fun P15 (Int) Bool)
(declare-fun P24 (Int) Bool)
(declare-fun P35 (Int) Bool)
(declare-fun P31 (Int) Bool)
(declare-fun P4 (Int) Bool)
(declare-fun P8 (Int) Bool)
(declare-fun P5 (Bool) Bool)
(declare-fun P3 (Int) Bool)
(declare-fun P9 (Int) Bool)
(declare-fun P40 (Bool) Bool)
(declare-fun P44 (Int) Bool)
(declare-fun P49 (Int) Bool)
(declare-fun P37 (Int) Bool)
(declare-fun P19 (Int) Bool)
(declare-fun P21 (Int) Bool)
(declare-fun P33 (Int) Bool)
(declare-fun P6 (Int) Bool)
(declare-fun P26 (Int) Bool)
(declare-fun P25 (Int) Bool)
(declare-fun P12 (Int) Bool)
(declare-fun P43 (Int) Bool)
(declare-fun P45 (Int) Bool)
(declare-fun P7 (Int) Bool)
(declare-fun P61 (Int) Bool)
(declare-fun P32 (Int) Bool)
(declare-fun P34 (Int) Bool)
(declare-fun P11 (Int) Bool)
(declare-fun P59 (Int) Bool)
(declare-fun P13 (Int) Bool)
(declare-fun P14 (Int) Bool)
(declare-fun P29 (Int) Bool)
(declare-fun P17 (Int) Bool)
(declare-fun P23 (Int) Bool)
(declare-fun P39 (Int) Bool)
(declare-fun P10 (Int) Bool)
(declare-fun P53 (Int) Bool)
(declare-fun P52 (Int) Bool)
(declare-fun P46 (Int) Bool)
(declare-fun P1 (Int) Bool)
(declare-fun P18 (Bool) Bool)
(declare-fun P50 (Int) Bool)
(declare-fun P30 (Bool) Bool)
(declare-fun P51 (Int) Bool)
(declare-fun P36 (Int) Bool)
(declare-fun P41 (Int) Bool)
(declare-fun P42 (Bool) Bool)
(declare-fun P47 (Int) Bool)
(declare-fun P38 (Int) Bool)
(declare-fun P48 (Int) Bool)
(assert (forall ((r Int)) (=> (P0 r) (>= r 2))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P22 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P20 r))))
(assert (forall ((r Int)) (=> (P27 r) (P54 r))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P24 r) (P2 c0) (= c0 false) true) (P15 r))))
(assert (forall ((r Int)) (=> (P31 r) (P35 r))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P22 r) (P2 c0) (= c0 false) true) (P20 r))))
(assert (forall ((r Int)) (=> (and (P8 r) true) (P4 r))))
(assert (forall ((r1 Int) (r2 Int)) (=> (and (P4 r1) (P3 r2) true) (P5 (= r1 r2)))))
(assert (forall ((c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 true)
           true)
      (P9 0))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P49 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P44 r))))
(assert (forall ((c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P9 0))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P54 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P37 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P21 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P19 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P33 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P31 r))))
(assert (forall ((r Int)) (=> (P6 r) (P8 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool))
  (=> (and (P12 r1) (P25 r2) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true)
      (P26 (+ r1 r2)))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P45 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P43 r))))
(assert (forall ((c0 Bool) (c1 Bool))
  (=> (and (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P7 10))))
(assert (forall ((r Int)) (=> (and (P61 r) true) (P0 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P34 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P32 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P9 r)
           (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 true)
           true)
      (P3 r))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P59 r) (P2 c0) (= c0 false) true) (P11 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P20 r1)
           (P12 r2)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P21 (- r1 r2)))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool))
  (=> (and (P12 r1) (P11 r2) (P2 c0) (= c0 false) true) (P13 (+ r1 r2)))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P14 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P12 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P35 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P29 r))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P23 r) (P2 c0) (= c0 false) true) (P17 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P3 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P39 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P7 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P6 r))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P13 r) (P2 c0) (= c0 false) true) (P10 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P12 r1)
           (P52 r2)
           (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 false)
           true)
      (P53 (+ r1 r2)))))
(assert (forall ((r Int)) (=> (P6 r) (P22 r))))
(assert (forall ((r Bool)) (=> (and (P5 r) true) (P2 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool))
  (=> (and (P20 r1) (P12 r2) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true)
      (P21 (- r1 r2)))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P34 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P32 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P32 r1)
           (P12 r2)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P33 (- r1 r2)))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P21 r) (P2 c0) (= c0 false) true) (P19 r))))
(assert (forall ((r Int)) (=> (P46 r) (P49 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P22 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P20 r))))
(assert (forall ((r Int)) (=> (P1 r) (P61 r))))
(assert (forall ((r Int)) (=> (P19 r) (P23 r))))
(assert (forall ((r Int)) (=> (P15 r) (P59 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool))
  (=> (and (P32 r1) (P12 r2) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true)
      (P33 (- r1 r2)))))
(assert (forall ((c0 Bool)) (=> (and (P2 c0) (= c0 false) true) (P14 1))))
(assert (forall ((r Bool) (c0 Bool))
  (=> (and (P18 r) (P2 c0) (= c0 false) true) (P16 r))))
(assert (forall ((c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P7 10))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P26 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P24 r))))
(assert (forall ((r Int)) (=> (P43 r) (P50 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool))
  (=> (and (P17 r1) (P3 r2) (P2 c0) (= c0 false) true) (P18 (= r1 r2)))))
(assert (P9 0))
(assert (forall ((c0 Bool)) (=> (and (P2 c0) (= c0 false) true) (P7 10))))
(assert (forall ((r Bool) (c0 Bool) (c1 Bool))
  (=> (and (P30 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P28 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P51 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P39 r))))
(assert (forall ((r Int) (c0 Bool))
  (=> (and (P14 r) (P2 c0) (= c0 false) true) (P12 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P36 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P27 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P9 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P3 r))))
(assert (forall ((c0 Bool) (c1 Bool))
  (=> (and (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P14 1))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P50 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P41 r))))
(assert (forall ((c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 false)
           true)
      (P14 1))))
(assert (forall ((c0 Bool) (c1 Bool))
  (=> (and (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P9 0))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P54 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P25 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P53 r)
           (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 false)
           true)
      (P51 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P41 r1)
           (P3 r2)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P42 (= r1 r2)))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P49 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P47 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P54 r)
           (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 false)
           true)
      (P52 r))))
(assert (forall ((r Bool) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P42 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P40 r))))
(assert (forall ((r Int) (c0 Bool)) (=> (and (P9 r) (P2 c0) (= c0 false) true) (P3 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P12 r1)
           (P37 r2)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P38 (+ r1 r2)))))
(assert (P7 10))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P44 r1)
           (P12 r2)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P45 (- r1 r2)))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool))
  (=> (and (P20 r1) (P12 r2) (P2 c0) (= c0 false) true) (P21 (- r1 r2)))))
(assert (forall ((c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P14 1))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P33 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P46 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P48 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P46 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool))
  (=> (and (P29 r1) (P3 r2) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true)
      (P30 (= r1 r2)))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P7 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P6 r))))
(assert (forall ((r Int)) (=> (P39 r) (P54 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool) (c3 Bool))
  (=> (and (P14 r)
           (P2 c3)
           (= c3 false)
           (P16 c2)
           (= c2 false)
           (P28 c1)
           (= c1 false)
           (P40 c0)
           (= c0 false)
           true)
      (P12 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P33 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P43 r))))
(assert (forall ((r1 Int) (r2 Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P47 r1)
           (P12 r2)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P48 (- r1 r2)))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P38 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P36 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P21 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P19 r))))
(assert (forall ((r Int) (c0 Bool)) (=> (and (P7 r) (P2 c0) (= c0 false) true) (P6 r))))
(assert (forall ((r Int)) (=> (and (P7 r) true) (P6 r))))
(assert (forall ((r Int)) (=> (and (P10 r) true) (P1 r))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool) (c2 Bool))
  (=> (and (P14 r)
           (P2 c2)
           (= c2 false)
           (P16 c1)
           (= c1 false)
           (P28 c0)
           (= c0 false)
           true)
      (P12 r))))
(assert (forall ((r Int)) (=> (P19 r) (P34 r))))
(assert (forall ((c0 Bool)) (=> (and (P2 c0) (= c0 false) true) (P9 0))))
(assert (forall ((r Int) (c0 Bool) (c1 Bool))
  (=> (and (P9 r) (P2 c1) (= c1 false) (P16 c0) (= c0 false) true) (P3 r))))
(assert (forall ((r Int)) (=> (and (P9 r) true) (P3 r))))
(check-sat)
(get-model)
