name: Build project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - "dev"
        ocaml_version:
          - "4.14.1-flambda"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: "dde.opam"
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build project"
              dune build program_analysis
              dune build formal
            endGroup
      - name: Revert permissions
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
